"use client";
// Chart analysis surface — NEPSE and crypto, one engine.
//
// Renders a computed analysis. Nothing on this page is generated by a language
// model, and nothing here is advice: every number traces to lib/analysis/*, the
// verdict can say AVOID or WAIT, and the conflicts are shown above the agreements.
import { useCallback, useEffect, useState } from "react";
import "../nepse/nepse.css";

const NEPSE = ["NABIL", "NICA", "SCB", "EBL", "GBIME", "NRIC", "NLIC", "CHCL", "UPPER", "API", "SHIVM", "CBBL", "SANIMA", "PRVU"];
const CRYPTO = ["BTCUSDT", "ETHUSDT"];

const DIR_COLOR = { BULLISH: "var(--accent)", BEARISH: "var(--down)", NEUTRAL: "var(--text-dim)", UNAVAILABLE: "var(--text-faint)" };
const BIAS_TONE = { BULLISH: "up", BEARISH: "down", CONFLICTED: "pro", NEUTRAL: "neutral", INSUFFICIENT_EVIDENCE: "pro" };

const fmt = (n) => (typeof n === "number" ? n.toLocaleString(undefined, { maximumFractionDigits: 2 }) : "—");

export default function AnalysisPage() {
  const [market, setMarket] = useState("nepse");
  const [symbol, setSymbol] = useState("NABIL");
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [narr, setNarr] = useState(null);
  const [narrating, setNarrating] = useState(false);

  const run = useCallback(async (m, s) => {
    setLoading(true); setError(""); setData(null);
    try {
      const r = await fetch(`/api/analysis?market=${m}&symbol=${s}`, { cache: "no-store" });
      const d = await r.json();
      if (!d.ok) setError(d.reason || "analysis unavailable");
      else setData(d.analysis);
    } catch { setError("unreachable"); }
    setLoading(false);
  }, []);

  // Narration asks the server to explain the analysis it already computed. The
  // browser sends only market+symbol — never a prompt — and the server withholds
  // any reply that introduces a number or reads as advice.
  const narrate = useCallback(async () => {
    setNarrating(true); setNarr(null);
    try {
      const r = await fetch("/api/analysis/narrate", {
        method: "POST", headers: { "content-type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ market, symbol }),
      });
      setNarr(await r.json());
    } catch { setNarr({ ok: false, reason: "unreachable" }); }
    setNarrating(false);
  }, [market, symbol]);

  useEffect(() => { run(market, symbol); setNarr(null); }, [run, market, symbol]);

  const list = market === "crypto" ? CRYPTO : NEPSE;
  const a = data;
  const c = a?.confluence;

  return (
    <div className="nepse-root page shell-page">
      <div className="nepse-wrap" style={{ paddingTop: "1.5rem" }}>
        <div className="nepse-banner">
          <span className="nepse-chip warn">Research &amp; observation only — not investment advice</span>
          <span className="nepse-chip">No order · no size · Guardian still governs</span>
          {a ? <span className="nepse-chip">{a.source}</span> : null}
        </div>

        <header className="nepse-head">
          <div className="nepse-eyebrow">Chart analysis</div>
          <h1 className="nepse-title">What this chart is doing</h1>
          <p className="nepse-dek">
            Trend, structure, levels, momentum and volume — computed, then weighed against
            each other. Conflicts are shown before agreements, and “wait” is a valid answer.
          </p>
        </header>

        <div className="nepse-row" style={{ margin: "1rem 0 1.5rem" }}>
          <select className="nepse-select" value={market}
            onChange={(e) => { const m = e.target.value; setMarket(m); setSymbol(m === "crypto" ? "BTCUSDT" : "NABIL"); }}>
            <option value="nepse">NEPSE</option>
            <option value="crypto">Crypto</option>
          </select>
          <select className="nepse-select" value={symbol} onChange={(e) => setSymbol(e.target.value)}>
            {list.map((s) => <option key={s}>{s}</option>)}
          </select>
          <button className="nepse-btn" onClick={() => run(market, symbol)} disabled={loading}>
            {loading ? "analysing…" : "re-run"}
          </button>
          <button className="nepse-btn ghost" onClick={narrate} disabled={!data || narrating}>
            {narrating ? "explaining…" : "explain this"}
          </button>
        </div>

        {error ? <div className="nepse-callout" style={{ borderLeftColor: "var(--down)", background: "var(--down-soft)" }}>Could not analyse: {error}</div> : null}
        {loading && !a ? <div className="nepse-empty">Computing from history…</div> : null}

        {a ? (
          <>
            {/* headline */}
            <div className="nepse-card" style={{ marginBottom: "1rem" }}>
              <div className="nepse-row" style={{ justifyContent: "space-between", alignItems: "flex-start" }}>
                <div>
                  <div className="nepse-row" style={{ gap: "0.9rem", alignItems: "baseline" }}>
                    <h2 className="nepse-title" style={{ fontSize: "1.7rem" }}>{a.instrument}</h2>
                    <span className="nepse-stat num">{fmt(a.price)}</span>
                    <span className={`nepse-badge ${BIAS_TONE[c.bias] || "neutral"}`}>{c.bias.replace(/_/g, " ")}</span>
                    <span className="nepse-chip">confidence {c.confidence}</span>
                  </div>
                  <div className="mono" style={{ fontSize: "0.72rem", color: "var(--text-faint)", marginTop: "0.4rem" }}>
                    as of {a.asOf} · {a.observations} bars · {a.adjustment}
                  </div>
                </div>
                <div style={{ textAlign: "right" }}>
                  <div className="mono" style={{ fontSize: "0.66rem", letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--text-faint)" }}>Verdict</div>
                  <div style={{ fontFamily: "'Fraunces',serif", fontSize: "1.05rem", fontWeight: 600, marginTop: 3 }}>{a.plan.verdict}</div>
                </div>
              </div>
            </div>

            <div className="nepse-grid-2" style={{ alignItems: "start" }}>
              {/* signals */}
              <div className="nepse-card">
                <h3>Signals</h3>
                <p style={{ color: "var(--text-dim)", fontSize: "0.85rem", margin: "0.2rem 0 0.9rem" }}>
                  {c.counts.bullish} bullish · {c.counts.bearish} bearish · {c.counts.neutral} neutral · {c.counts.unavailable} unavailable
                </p>
                <div style={{ display: "flex", flexDirection: "column" }}>
                  {a.signals.map((s) => (
                    <div key={s.name} style={{ display: "grid", gridTemplateColumns: "9px 1fr", gap: 11, padding: "0.55rem 0", borderTop: "1px solid var(--surface-2)" }}>
                      <span style={{ width: 9, height: 9, borderRadius: 2, background: DIR_COLOR[s.direction], marginTop: 6 }} />
                      <div>
                        <div style={{ fontSize: "0.9rem", fontWeight: 600 }}>{s.name}</div>
                        <div style={{ fontSize: "0.8rem", color: "var(--text-dim)" }}>{s.detail}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
                {/* conflicts first, deliberately */}
                <div className="nepse-card" style={{ borderLeft: "3px solid var(--down)" }}>
                  <h3>What conflicts</h3>
                  {c.conflicting.length ? (
                    <ul style={{ margin: "0.5rem 0 0", paddingLeft: "1.1rem", fontSize: "0.86rem", color: "var(--text-dim)", lineHeight: 1.65 }}>
                      {c.conflicting.map((x) => <li key={x.name}><b style={{ color: "var(--text)" }}>{x.name}</b> — {x.detail}</li>)}
                    </ul>
                  ) : <p style={{ margin: "0.4rem 0 0", fontSize: "0.86rem", color: "var(--text-dim)" }}>Nothing contradicts the read.</p>}
                  {c.unavailable.length ? (
                    <p className="mono" style={{ fontSize: "0.72rem", color: "var(--text-faint)", marginTop: "0.7rem" }}>
                      unavailable: {c.unavailable.map((x) => x.name).join(", ")}
                    </p>
                  ) : null}
                </div>

                {/* levels */}
                <div className="nepse-card">
                  <h3>Levels that matter</h3>
                  <div className="nepse-grid-2" style={{ gap: "1rem", marginTop: "0.6rem" }}>
                    <div>
                      <div className="mono" style={{ fontSize: "0.66rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--down)" }}>Resistance</div>
                      {a.levels.resistance.length ? a.levels.resistance.map((r) => (
                        <div key={r.price} style={{ display: "flex", justifyContent: "space-between", fontSize: "0.84rem", padding: "0.3rem 0" }}>
                          <span className="num">{fmt(r.price)}</span>
                          <span style={{ color: "var(--text-faint)" }}>{r.touches}× · {r.distancePct}%</span>
                        </div>
                      )) : <div style={{ fontSize: "0.82rem", color: "var(--text-faint)" }}>none established</div>}
                    </div>
                    <div>
                      <div className="mono" style={{ fontSize: "0.66rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--accent)" }}>Support</div>
                      {a.levels.support.length ? a.levels.support.map((s) => (
                        <div key={s.price} style={{ display: "flex", justifyContent: "space-between", fontSize: "0.84rem", padding: "0.3rem 0" }}>
                          <span className="num">{fmt(s.price)}</span>
                          <span style={{ color: "var(--text-faint)" }}>{s.touches}× · {s.distancePct}%</span>
                        </div>
                      )) : <div style={{ fontSize: "0.82rem", color: "var(--text-faint)" }}>none established</div>}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* setup + plan */}
            <div className="nepse-grid-2" style={{ marginTop: "1rem", alignItems: "start" }}>
              <div className="nepse-card">
                <h3>Setup · {a.setups[0].type.replace(/_/g, " ")}</h3>
                <p style={{ fontSize: "0.88rem", margin: "0.5rem 0 0.6rem" }}>{a.setups[0].case}</p>
                <div className="nepse-callout gold" style={{ fontSize: "0.84rem" }}>
                  <b>Tradeoff.</b> {a.setups[0].tradeoff}
                </div>
                {a.setups[0].confirmation?.length ? (
                  <>
                    <div className="mono" style={{ fontSize: "0.66rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--text-faint)", margin: "0.9rem 0 0.4rem" }}>Confirmation needed</div>
                    <ul style={{ margin: 0, paddingLeft: "1.1rem", fontSize: "0.84rem", color: "var(--text-dim)", lineHeight: 1.6 }}>
                      {a.setups[0].confirmation.map((x) => <li key={x}>{x}</li>)}
                    </ul>
                  </>
                ) : null}
              </div>

              <div className="nepse-card">
                <h3>Plan</h3>
                <table className="nepse-table" style={{ minWidth: 0, marginTop: "0.5rem" }}>
                  <tbody>
                    <tr><td style={{ color: "var(--text-dim)" }}>Entry</td><td className="rt num">{a.plan.entry ? `${a.plan.entry.type} ${fmt(a.plan.entry.from)}` : "none derived"}</td></tr>
                    <tr><td style={{ color: "var(--text-dim)" }}>Stop</td><td className="rt num">{a.plan.stop !== null ? fmt(a.plan.stop) : "none derived"}</td></tr>
                    <tr><td style={{ color: "var(--text-dim)" }}>Targets</td><td className="rt num">{a.plan.targets.length ? a.plan.targets.map((t) => fmt(t.price)).join(" · ") : "none derived"}</td></tr>
                    <tr><td style={{ color: "var(--text-dim)" }}>Reward : risk</td><td className={`rt num ${a.plan.riskReward >= 1.5 ? "nepse-up" : "nepse-down"}`}>{a.plan.riskReward !== null ? `${a.plan.riskReward}:1` : "not computable"}</td></tr>
                  </tbody>
                </table>
                {a.plan.notes.length ? (
                  <ul style={{ margin: "0.8rem 0 0", paddingLeft: "1.1rem", fontSize: "0.82rem", color: "var(--down)", lineHeight: 1.6 }}>
                    {a.plan.notes.map((n) => <li key={n}>{n}</li>)}
                  </ul>
                ) : null}
              </div>
            </div>

            {/* invalidation + challenge */}
            <div className="nepse-grid-2" style={{ marginTop: "1rem", alignItems: "start" }}>
              <div className="nepse-card">
                <h3>What would change this</h3>
                <ul style={{ margin: "0.5rem 0 0", paddingLeft: "1.1rem", fontSize: "0.85rem", color: "var(--text-dim)", lineHeight: 1.7 }}>
                  {a.invalidation.map((x) => <li key={x}>{x}</li>)}
                </ul>
              </div>
              <div className="nepse-card">
                <h3>The case against</h3>
                <ul style={{ margin: "0.5rem 0 0", paddingLeft: "1.1rem", fontSize: "0.85rem", color: "var(--text-dim)", lineHeight: 1.7 }}>
                  {a.challenge.overlooked.map((x) => <li key={x}>{x}</li>)}
                </ul>
                <p style={{ fontSize: "0.84rem", marginTop: "0.8rem" }}>
                  <b>What would convince otherwise:</b> {a.challenge.wouldConvince}
                </p>
              </div>
            </div>

            {narr ? (
              <div className="nepse-card" style={{ marginTop: "1rem", borderLeft: "3px solid var(--accent)" }}>
                <div className="nepse-row" style={{ justifyContent: "space-between", alignItems: "baseline" }}>
                  <h3>Explanation</h3>
                  <span className="mono" style={{ fontSize: "0.66rem", color: "var(--text-faint)" }}>
                    {narr.model ? `model ${narr.model}` : ""}
                  </span>
                </div>
                {narr.ok && narr.narration ? (
                  <>
                    <div style={{ fontSize: "0.9rem", lineHeight: 1.7, whiteSpace: "pre-line", marginTop: "0.6rem" }}>
                      {narr.narration}
                    </div>
                    <p className="mono" style={{ fontSize: "0.68rem", color: "var(--text-faint)", marginTop: "0.9rem" }}>
                      Verified: {narr.gate?.numeric?.checked ?? 0} figures checked against the computed facts — none invented.
                    </p>
                  </>
                ) : narr.withheld ? (
                  <div className="nepse-callout" style={{ borderLeftColor: "var(--down)", background: "var(--down-soft)", marginTop: "0.6rem" }}>
                    <b>Explanation withheld.</b> The model {narr.gate?.reason === "INVENTED_NUMBERS"
                      ? `introduced ${narr.gate.numeric.invented.length} figure(s) absent from the computed facts (${narr.gate.numeric.invented.slice(0, 4).join(", ")})`
                      : "produced text that reads as advice"}. The analysis above stands on its own.
                  </div>
                ) : (
                  <p style={{ fontSize: "0.85rem", color: "var(--text-dim)", marginTop: "0.6rem" }}>
                    {narr.reason === "NOT_SIGNED_IN"
                      ? "Sign in to have this explained — narration calls a model, so it stays behind auth."
                      : `Could not explain: ${narr.reason}${narr.detail ? ` — ${narr.detail}` : ""}.`} The computed analysis above is unaffected.
                  </p>
                )}
              </div>
            ) : null}

            <p className="mono" style={{ fontSize: "0.7rem", color: "var(--text-faint)", marginTop: "1.2rem", lineHeight: 1.6 }}>
              {a.authority.note}
            </p>
          </>
        ) : null}
      </div>
    </div>
  );
}
