"""Market-data error codes. Fail-closed."""
from __future__ import annotations


class MarketDataError(Exception):
    def __init__(self, code: str, message: str, details: dict | None = None):
        self.code = code
        self.message = message
        self.details = details or {}
        super().__init__(f"{code}: {message}")


# Fail-closed codes (subset used by service/certification)
UNREGISTERED_DATASET = "UNREGISTERED_DATASET"
DATASET_REVOKED = "DATASET_REVOKED"
DATASET_QUARANTINED = "DATASET_QUARANTINED"
LICENCE_UNKNOWN = "LICENCE_UNKNOWN"
LICENCE_FORBIDDEN = "LICENCE_FORBIDDEN"
LICENCE_GATE_FAILED = "LICENCE_GATE_FAILED"
PROVENANCE_INCOMPLETE = "PROVENANCE_INCOMPLETE"
CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
CHECKSUM_MISSING = "CHECKSUM_MISSING"
INGESTION_FAILED = "INGESTION_FAILED"
QUALITY_BLOCKING = "QUALITY_BLOCKING"
LOOKAHEAD_DETECTED = "LOOKAHEAD_DETECTED"
SURVIVORSHIP_UNREPORTED = "SURVIVORSHIP_UNREPORTED"
DATA_LEAKAGE = "DATA_LEAKAGE"
FEATURE_LINEAGE_FAILED = "FEATURE_LINEAGE_FAILED"
SIGNAL_VALIDATION_BLOCKED = "SIGNAL_VALIDATION_BLOCKED"
AUTHORITY_VIOLATION = "AUTHORITY_VIOLATION"
BROKER_ISOLATION = "BROKER_ISOLATION"
CREDENTIAL_REJECTED = "CREDENTIAL_REJECTED"
PATH_TRAVERSAL = "PATH_TRAVERSAL"
UNSAFE_FILE = "UNSAFE_FILE"
OVERSIZED_INPUT = "OVERSIZED_INPUT"
SYNTHETIC_MISLABEL = "SYNTHETIC_MISLABEL"
VERSION_COLLISION = "VERSION_COLLISION"
