"""M164 — Private-alpha incident playbooks (detection → escalation boundary)."""
from __future__ import annotations

from typing import Any

INCIDENT_PLAYBOOKS: dict[str, dict[str, Any]] = {
    "backend_will_not_start": {
        "id": "backend_will_not_start",
        "detection": "saathi-local doctor shows backend DOWN; health HTTP not 200",
        "severity": "high",
        "containment": "Do not open public ports; leave unrelated processes untouched",
        "diagnosis": "bin/saathi-alpha doctor; bin/saathi-local logs --backend; check port 8765",
        "safe_remediation": "Fix port conflict or env; saathi-local restart (owned only)",
        "rollback": "saathi-local stop; restore last known-good config if corrupted",
        "evidence": "support bundle + backend.log tail (redacted)",
        "escalation_boundary": "private-alpha owner only; no production ops",
    },
    "frontend_will_not_start": {
        "id": "frontend_will_not_start",
        "detection": "frontend port not ready; /platform not 200",
        "severity": "high",
        "containment": "Do not kill unrelated node processes",
        "diagnosis": "doctor; logs --frontend; verify saathi-os/node_modules",
        "safe_remediation": "npm install in saathi-os; saathi-local restart",
        "rollback": "stop frontend; use previous node_modules if available",
        "evidence": "frontend.log + doctor checks",
        "escalation_boundary": "owner",
    },
    "port_conflict": {
        "id": "port_conflict",
        "detection": "doctor reports unrelated PID on 8765/3000",
        "severity": "medium",
        "containment": "Refuse to kill unrelated PID (fail-closed)",
        "diagnosis": "lsof -nP -iTCP:8765 -sTCP:LISTEN",
        "safe_remediation": "Stop the process you own, or change config ports carefully",
        "rollback": "n/a",
        "evidence": "listener report in support bundle",
        "escalation_boundary": "owner machine admin",
    },
    "stale_process": {
        "id": "stale_process",
        "detection": "PID file present but process not owned/alive",
        "severity": "low",
        "containment": "Do not kill by name",
        "diagnosis": "saathi-local doctor stale pid lines",
        "safe_remediation": "Remove stale PID files under ~/.saathi/run after confirmation",
        "rollback": "n/a",
        "evidence": "launcher.log",
        "escalation_boundary": "owner",
    },
    "database_locked": {
        "id": "database_locked",
        "detection": "SQLite locked errors in backend log",
        "severity": "high",
        "containment": "Stop duplicate backend instances (owned only)",
        "diagnosis": "status; ensure single backend; db-check",
        "safe_remediation": "saathi-local restart after single-instance confirmation",
        "rollback": "restore from system backup if corruption suspected",
        "evidence": "db integrity report",
        "escalation_boundary": "owner",
    },
    "migration_failure": {
        "id": "migration_failure",
        "detection": "upgrade smoke fails; schema error",
        "severity": "high",
        "containment": "Halt upgrade; do not force live destructive restore",
        "diagnosis": "upgrade state file; prepare checks",
        "safe_remediation": "rollback_upgrade; restore config history",
        "rollback": "python -m saathi.platform.private_alpha upgrade-rollback",
        "evidence": "upgrade_state.json + pre-upgrade backup",
        "escalation_boundary": "owner",
    },
    "backup_failure": {
        "id": "backup_failure",
        "detection": "create_system_backup raises or verify fails",
        "severity": "high",
        "containment": "Do not delete existing backups",
        "diagnosis": "disk headroom; path permissions; symlink checks",
        "safe_remediation": "free disk; fix backup path; retry",
        "rollback": "n/a",
        "evidence": "backup error + disk report",
        "escalation_boundary": "owner",
    },
    "restore_failure": {
        "id": "restore_failure",
        "detection": "restore returns ok=false or integrity mismatch",
        "severity": "critical",
        "containment": "Keep pre-restore checkpoint; isolated restore only",
        "diagnosis": "verify_system_backup; dry_run_restore",
        "safe_remediation": "Use known-good archive; never skip integrity",
        "rollback": "restore pre-restore checkpoint",
        "evidence": "verification details",
        "escalation_boundary": "owner",
    },
    "automation_stuck": {
        "id": "automation_stuck",
        "detection": "run state RUNNING beyond timeout",
        "severity": "medium",
        "containment": "cancel_run; disable automation",
        "diagnosis": "list_runs; audit automation.run.*",
        "safe_remediation": "cancel; fix action; re-validate; re-enable",
        "rollback": "disable automation; global flag off",
        "evidence": "run record + audit",
        "escalation_boundary": "owner/operator",
    },
    "worker_lease_stale": {
        "id": "worker_lease_stale",
        "detection": "worker lease age exceeds threshold",
        "severity": "medium",
        "containment": "Do not invent a second worker system",
        "diagnosis": "platform ops / release health",
        "safe_remediation": "restart owned runtime; reconcile via existing ops",
        "rollback": "stop services",
        "evidence": "health metrics",
        "escalation_boundary": "owner",
    },
    "browser_cannot_open": {
        "id": "browser_cannot_open",
        "detection": "saathi-local open fails readiness gate",
        "severity": "medium",
        "containment": "Do not disable fail-closed open gate",
        "diagnosis": "status + doctor",
        "safe_remediation": "start services; resolve blockers; open again",
        "rollback": "n/a",
        "evidence": "launcher.log",
        "escalation_boundary": "owner",
    },
    "disk_space_low": {
        "id": "disk_space_low",
        "detection": "disk_headroom FAIL in prepare/doctor",
        "severity": "high",
        "containment": "Stop unbounded log growth; prune backups carefully",
        "diagnosis": "df -h; storage report",
        "safe_remediation": "Free space; prune_system_backups keep>=3",
        "rollback": "n/a",
        "evidence": "disk metrics",
        "escalation_boundary": "owner",
    },
    "memory_pressure": {
        "id": "memory_pressure",
        "detection": "swap thrash; browser unresponsive; high RSS",
        "severity": "high",
        "containment": "Stop nonessential local apps; pause automations",
        "diagnosis": "resource metrics in support bundle",
        "safe_remediation": "restart services; reduce concurrent workflows",
        "rollback": "stop services",
        "evidence": "resource report",
        "escalation_boundary": "owner",
    },
    "corrupt_configuration": {
        "id": "corrupt_configuration",
        "detection": "config validation fails",
        "severity": "high",
        "containment": "Do not accept secret-shaped keys",
        "diagnosis": "load_config/validate_config error",
        "safe_remediation": "rollback_config from history",
        "rollback": "config history restore",
        "evidence": "config error message (redacted)",
        "escalation_boundary": "owner",
    },
    "session_failure": {
        "id": "session_failure",
        "detection": "auth failures; SESSION_INVALID",
        "severity": "medium",
        "containment": "Do not log tokens",
        "diagnosis": "login with known local account; check session table integrity",
        "safe_remediation": "re-login; rotate session if available",
        "rollback": "n/a",
        "evidence": "audit session events (no tokens)",
        "escalation_boundary": "owner",
    },
    "approval_backlog": {
        "id": "approval_backlog",
        "detection": "pending approvals grow unbounded",
        "severity": "medium",
        "containment": "Do not auto-approve",
        "diagnosis": "operator home approvals list",
        "safe_remediation": "owner/operator reviews via Approval Center",
        "rollback": "n/a",
        "evidence": "approval counts",
        "escalation_boundary": "owner/operator",
    },
    "unexpected_public_listener": {
        "id": "unexpected_public_listener",
        "detection": "doctor public_listener_regression true",
        "severity": "critical",
        "containment": "Stop Saathi services immediately if they bind public",
        "diagnosis": "lsof listeners; launcher source scan",
        "safe_remediation": "Restore localhost-only binds; never re-enable public",
        "rollback": "stop services; restore launcher from git",
        "evidence": "listener report + support bundle",
        "escalation_boundary": "owner — security incident",
    },
    "provider_unavailable": {
        "id": "provider_unavailable",
        "detection": "optional local provider missing",
        "severity": "low",
        "containment": "Do not activate paid providers automatically",
        "diagnosis": "config local_provider_choices",
        "safe_remediation": "Continue with fixtures/local_only",
        "rollback": "n/a",
        "evidence": "provider posture",
        "escalation_boundary": "owner",
    },
}


def playbook_for(incident_id: str) -> dict[str, Any]:
    pb = INCIDENT_PLAYBOOKS.get(incident_id)
    if not pb:
        return {
            "id": incident_id,
            "error": "UNKNOWN_INCIDENT",
            "escalation_boundary": "owner",
            "containment": "fail closed; collect support bundle",
        }
    return dict(pb)


def list_playbooks() -> list[dict[str, Any]]:
    return [playbook_for(k) for k in sorted(INCIDENT_PLAYBOOKS)]
